
-- Create site_settings table
create table public.site_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  key text not null unique,
  value text
);

-- Enable RLS
alter table public.site_settings enable row level security;

-- Policies
create policy "Allow public read access" on public.site_settings for select to public using (true);
create policy "Allow internal write access" on public.site_settings for insert to authenticated with check (true);
create policy "Allow internal update access" on public.site_settings for update to authenticated using (true);

-- Insert default running text if not exists
insert into public.site_settings (key, value)
values ('running_text', 'Selamat Datang di Yeobo Land - Hunian Impian Keluarga Anda di Bekasi!')
on conflict (key) do nothing;
